### ISSUE TITLE
Run failure

### ISSUE THREAD

**Issue by haylinmoore** [utterance/utterances-oauth#3]
I installed by cloning the repo, then npm install, followed by npm run-script build, I cded into dist and ran index.js. My node version is 8.0.0, but I have tried with 10.15.3 aswell

root@server:/var/www/utterances-oauth/dist# node index.js 
/var/www/utterances-oauth/dist/index.js:276
  addEventListener('fetch', e => {
  ^

ReferenceError: addEventListener is not defined
    at /var/www/utterances-oauth/dist/index.js:276:3
    at Object.<anonymous> (/var/www/utterances-oauth/dist/index.js:281:2)
    at Module._compile (module.js:569:30)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:503:32)
    at tryModuleLoad (module.js:466:12)
    at Function.Module._load (module.js:458:3)
    at Function.Module.runMain (module.js:605:10)
    at startup (bootstrap_node.js:158:16)
    at bootstrap_node.js:575:3

**Comment by jdanyow** [comment]
@herohamp I've updated the readme. This project builds a script intended to be run in the Cloudflare worker environment. You'd need to use https://github.com/gja/cloudflare-worker-local to debug it locally.
